/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f4xx.h"
#include "stm32f407xx.h"
#include "Helpers/logger.h"

#define ENABLE_OUTPUT() SET_BIT(GPIOD->ODR,GPIO_ODR_OD12)

#define DISABLE_OUTPUT() CLEAR_BIT(GPIOD->ODR,GPIO_ODR_OD12)

#define GET_INPUT_STATE() READ_BIT(GPIOA->IDR,GPIO_IDR_ID0)

static volatile uint32_t gMsTicks = 0;

void SysTick_Handler() {
	if (GET_INPUT_STATE() == true)
		ENABLE_OUTPUT();
	else
		DISABLE_OUTPUT();
	gMsTicks++;
}

void TIM1_UP_IRQHandler(void) {                 // Timer Interrupt Handler
}

static void ConfigureOutputGpio(void) {
	// Enable GPIOD port clock
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);

	// Set PD12 to output mode
	MODIFY_REG(GPIOD->MODER, GPIO_MODER_MODE12, _VAL2FLD(GPIO_MODER_MODE12,1));
}

static void ConfigureInputGpio(void) {

	// Enable GPIOA port clock
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);

	// Set PD12 to output mode
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE0, _VAL2FLD(GPIO_MODER_MODE0,0));
}

int main(void) {

	log_info("program entry point %d\n", 123);

	ConfigureOutputGpio();
	ConfigureInputGpio();

	SysTick_Config(SystemCoreClock / 72000);
	NVIC_SetPriority(TIM1_UP_TIM10_IRQn, 1);            // Set Timer priority
	NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);                 // Enable Timer Interrupt

	/* Loop forever */
	for (;;) {
	}
}
